In [ ]:
%pip install pandas numpy matplotlib seaborn


In [1]:
import numpy as np



In [6]:
classNum = int(input("How many student are in the csc 102 class?"))
class_arr = np.array(classNum)
if (class_arr== 1):
    print("There is only",class_arr,"student in csc 102 class")
else:
    print("There are",class_arr,"student in csc 102 class")

How many student are in the csc 102 class? 1


There is only 1 student in csc 102 class


In [7]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


In [9]:
arr =np.array([[1,2,3],[4,5,6],[7,9,8]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 9 8]]
(3, 3)


In [10]:
arr =np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(3, 2, 3)


In [14]:
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('the 5th element on 2nd row:',arr[1,4])

the 5th element on 2nd row: 10


In [18]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y,x)

1 [1 2 3]
2 [1 2 3]
3 [1 2 3]
4 [4 5 6]
5 [4 5 6]
6 [4 5 6]


In [20]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
 print(x[1,0])
 print(x[0,1])

4
2
10
8


In [25]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
       for z in y:
        print(z,y,x)

1 [1 2 3] [[1 2 3]
 [4 5 6]]
2 [1 2 3] [[1 2 3]
 [4 5 6]]
3 [1 2 3] [[1 2 3]
 [4 5 6]]
4 [4 5 6] [[1 2 3]
 [4 5 6]]
5 [4 5 6] [[1 2 3]
 [4 5 6]]
6 [4 5 6] [[1 2 3]
 [4 5 6]]
7 [7 8 9] [[ 7  8  9]
 [10 11 12]]
8 [7 8 9] [[ 7  8  9]
 [10 11 12]]
9 [7 8 9] [[ 7  8  9]
 [10 11 12]]
10 [10 11 12] [[ 7  8  9]
 [10 11 12]]
11 [10 11 12] [[ 7  8  9]
 [10 11 12]]
12 [10 11 12] [[ 7  8  9]
 [10 11 12]]


In [ ]:
#pandas
import pandas as pd
