In [1]:
%pip install pandas numpy matplotlib seaborn


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy


In [3]:
import numpy as np
print(np.__version__)

2.3.5


In [5]:
classnum = int(input("How many students are in the CSC 102 class?"))
class_arr = np.array(classnum)
if (class_arr == 1):
    print("There is only",class_arr,"student in CSC 102 class")
else:
    print("There are",class_arr,"students in CSC 102 class")

How many students are in the CSC 102 class? 1


There is only 1 student in CSC 102 class


In [6]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr.shape)

[1 2 3 4 5 6 7]
(7,)


In [20]:
arr = np.array([[1,2,3],[4,5,6],[2,5,7]])
print (arr)
print (arr.shape)
for x in arr:
    for y in x:
        print(y,x)
        

[[1 2 3]
 [4 5 6]
 [2 5 7]]
(3, 3)
1 [1 2 3]
2 [1 2 3]
3 [1 2 3]
4 [4 5 6]
5 [4 5 6]
6 [4 5 6]
2 [2 5 7]
5 [2 5 7]
7 [2 5 7]


In [22]:
arr = np.array([[[1,2,3],[2,3,4]],[[2,5,6],[3,5,7]],[[3,6,9],[5,7,9]]])
print (arr)
print(arr.shape)

for x in arr:
    for y in x:
        print(y,x)

[[[1 2 3]
  [2 3 4]]

 [[2 5 6]
  [3 5 7]]

 [[3 6 9]
  [5 7 9]]]
(3, 2, 3)
[1 2 3] [[1 2 3]
 [2 3 4]]
[2 3 4] [[1 2 3]
 [2 3 4]]
[2 5 6] [[2 5 6]
 [3 5 7]]
[3 5 7] [[2 5 6]
 [3 5 7]]
[3 6 9] [[3 6 9]
 [5 7 9]]
[5 7 9] [[3 6 9]
 [5 7 9]]


In [17]:
arr = np.array([[[1,2,3,4],[2,3,4,5]],[[2,5,6,7],[3,5,7,8]],[[3,6,9,10],[5,7,9,11]]])
print (arr)
print(arr.shape)
print(arr[2,1,2])
print(arr[1:2:2])

[[[ 1  2  3  4]
  [ 2  3  4  5]]

 [[ 2  5  6  7]
  [ 3  5  7  8]]

 [[ 3  6  9 10]
  [ 5  7  9 11]]]
(3, 2, 4)
9
[[[2 5 6 7]
  [3 5 7 8]]]


In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [5]:
#Iterate on each scalar element of the 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y,x)

1 [1 2 3]
2 [1 2 3]
3 [1 2 3]
4 [4 5 6]
5 [4 5 6]
6 [4 5 6]


In [3]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 1st dim: ', arr[0, -1])


Last element from 1st dim:  5


In [6]:
# Iterate on the elements of the following 3-D array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

#print(arr)

for x in arr:
    print(x[1,0])

    print(x[0,1])

4
2
10
8


In [7]:
#this tells u everything about the comand
np.array?



Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [8]:
# Access splitted arrays

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)


print(newarr[1])

[3 4]
